# Generated by Django 5.0.6 on 2025-01-21 10:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0005_chatroom_chat_export_alter_chatexport_export"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatroom",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
